# Generated by Django 6.0.2 on 2026-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='returned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
