# Generated by Django 6.0.2 on 2026-03-11 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addaccount_slug'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtType', models.CharField(choices=[('borrowed', 'Borrowed'), ('lent', 'Lent')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_lent_from', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('Family', 'Family'), ('Friend', 'Friend'), ('Colleague', 'Colleague'), ('Bank', 'Bank'), ('Other', 'Other')], max_length=50)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('duedate', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('repayment', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.addaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
