# Generated by Django 6.0.2 on 2026-03-12 08:36

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank Account'), ('Credit Card', 'Credit Card'), ('Savings', 'Savings Goal')], default='Cash', max_length=50)),
                ('accountName', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='accountName', unique=True)),
                ('accountBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('CAD', 'C$'), ('AUD', 'A$')], default='INR', max_length=10)),
                ('bankName', models.CharField(blank=True, max_length=100, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(choices=[('bi bi-cash-stack', 'Cash'), ('bi bi-building-fill', 'Bank'), ('bi bi-credit-card-2-front-fill', 'Credit Card'), ('bi bi-safe2-fill', 'Safe'), ('bi bi-graph-up-arrow', 'Investment'), ('bi bi-phone-fill', 'Phone'), ('bi bi-piggy-bank-fill', 'Piggy Bank'), ('bi bi-wallet2', 'Wallet'), ('bi bi-star-fill', 'Star'), ('bi bi-globe', 'Globe')], default='bi bi-cash-stack', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
