# Generated by Django 6.0.2 on 2026-02-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaccount',
            name='currency',
            field=models.CharField(choices=[('INR', '₹'), ('USD', '$'), ('EUR', '€'), ('GBP', '£'), ('JPY', '¥'), ('CAD', 'C$'), ('AUD', 'A$')], default='INR', max_length=10),
        ),
    ]
