# Generated by Django 6.0.2 on 2026-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_addaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaccount',
            name='cardColor',
            field=models.CharField(choices=[('#0F172A', 'Dark Navy'), ('#10B981', 'Emerald Green'), ('#38BDF8', 'Sky Blue'), ('#8B5CF6', 'Purple'), ('#EF4444', 'Red'), ('#F59E0B', 'Amber'), ('#EC4899', 'Pink'), ('#14B8A6', 'Teal'), ('#6366F1', 'Indigo'), ('#F97316', 'Orange')], default='#0F172A', max_length=7),
        ),
    ]
