# Generated by Django 6.0.2 on 2026-02-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_addaccount_cardcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addaccount',
            name='cardColor',
        ),
    ]
