# Generated by Django 6.0.2 on 2026-03-02 18:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_addaccount_cardcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='addaccount',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='accountName', unique=True),
        ),
    ]
